GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/60f173524a34d711343f8a11
###
POST http://localhost:3000/subscribers

Content-Type: application/json

{
    "name":"Goura",
    "subscribedToChannel":"Gourav Talks"
}

###

POST http://localhost:3000/subscribers

Content-Type: application/json

{
    "name":"Goura",
    "subscribedToChannel":"Gourav Talks"
}

###
 PATCH http://localhost:3000/subscribers/60f173524a34d711343f8a11

 Content-Type: application/json

 {
    "name":"Gour",
  
}

###

DELETE  http://localhost:3000/subscribers/60f173524a34d711343f8a11